In [2]:
import pandas as pd

In [21]:
t = pd.read_csv('..\data\Steel_industry_data.csv')

t.head()

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\Dario\AppData\Local\Temp\ipykernel_14016\3349589213.py:1: SyntaxWarning: invalid escape sequence '\d'
  t = pd.read_csv('..\data\Steel_industry_data.csv')

,date,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,WeekStatus,Day_of_week,Load_Type
0,01/01/2018 00:15,3.17,2.95,0.0,0.0,73.21,100.0,900,Weekday,Monday,Light_Load
1,01/01/2018 00:30,4.00,4.46,0.0,0.0,66.77,100.0,1800,Weekday,Monday,Light_Load
2,01/01/2018 00:45,3.24,3.28,0.0,0.0,70.28,100.0,2700,Weekday,Monday,Light_Load
3,01/01/2018 01:00,3.31,3.56,0.0,0.0,68.09,100.0,3600,Weekday,Monday,Light_Load
4,01/01/2018 01:15,3.82,4.50,0.0,0.0,64.72,100.0,4500,Weekday,Monday,Light_Load

In [11]:
t.info()

<class 'pandas.DataFrame'>
RangeIndex: 35040 entries, 0 to 35039
Data columns (total 11 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   date                                  35040 non-null  str
 1   Usage_kWh                             35040 non-null  float64
 2   Lagging_Current_Reactive.Power_kVarh  35040 non-null  float64
 3   Leading_Current_Reactive_Power_kVarh  35040 non-null  float64
 4   CO2(tCO2)                             35040 non-null  float64
 5   Lagging_Current_Power_Factor          35040 non-null  float64
 6   Leading_Current_Power_Factor          35040 non-null  float64
 7   NSM                                   35040 non-null  int64
 8   WeekStatus                            35040 non-null  str
 9   Day_of_week                           35040 non-null  str
 10  Load_Type                             35040 non-null  str
dtypes: float64(6), int64(1), str(4)
memory usage: 2.9 MB

In [16]:
# 2. Diccionario de traducción de columnas
nuevos_nombres = {
    'date': 'fecha',
    'Usage_kWh': 'consumo_kwh',
    'Lagging_Current_Reactive.Power_kVarh': 'reactiva_retraso_kvarh',
    'Leading_Current_Reactive_Power_kVarh': 'reactiva_adelanto_kvarh',
    'CO2(tCO2)': 'emisiones_co2',
    'Lagging_Current_Power_Factor': 'factor_potencia_retraso',
    'Leading_Current_Power_Factor': 'factor_potencia_adelanto',
    'NSM': 'segundos_desde_medianoche',
    'WeekStatus': 'estado_semana',
    'Day_of_week': 'dia_semana',
    'Load_Type': 'tipo_carga'
}

# Aplicar renombramiento
t.rename(columns=nuevos_nombres, inplace=True)

In [17]:
t.info()

<class 'pandas.DataFrame'>
RangeIndex: 35040 entries, 0 to 35039
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   fecha                      35040 non-null  str
 1   consumo_kwh                35040 non-null  float64
 2   reactiva_retraso_kvarh     35040 non-null  float64
 3   reactiva_adelanto_kvarh    35040 non-null  float64
 4   emisiones_co2              35040 non-null  float64
 5   factor_potencia_retraso    35040 non-null  float64
 6   factor_potencia_adelanto   35040 non-null  float64
 7   segundos_desde_medianoche  35040 non-null  int64
 8   estado_semana              35040 non-null  str
 9   dia_semana                 35040 non-null  str
 10  tipo_carga                 35040 non-null  str
dtypes: float64(6), int64(1), str(4)
memory usage: 2.9 MB

In [18]:
t.head()

,fecha,consumo_kwh,reactiva_retraso_kvarh,reactiva_adelanto_kvarh,emisiones_co2,factor_potencia_retraso,factor_potencia_adelanto,segundos_desde_medianoche,estado_semana,dia_semana,tipo_carga
0,01/01/2018 00:15,3.17,2.95,0.0,0.0,73.21,100.0,900,Weekday,Monday,Light_Load
1,01/01/2018 00:30,4.00,4.46,0.0,0.0,66.77,100.0,1800,Weekday,Monday,Light_Load
2,01/01/2018 00:45,3.24,3.28,0.0,0.0,70.28,100.0,2700,Weekday,Monday,Light_Load
3,01/01/2018 01:00,3.31,3.56,0.0,0.0,68.09,100.0,3600,Weekday,Monday,Light_Load
4,01/01/2018 01:15,3.82,4.50,0.0,0.0,64.72,100.0,4500,Weekday,Monday,Light_Load

In [20]:
x = pd.read_csv('..\data\periodos_peninsula.csv')

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\Dario\AppData\Local\Temp\ipykernel_14016\4162672071.py:1: SyntaxWarning: invalid escape sequence '\d'
  x = pd.read_csv('..\data\periodos_peninsula.csv')

In [22]:
x.head()

   hour  weekday period
0     0  weekday     P6
1     1  weekday     P6
2     2  weekday     P6
3     3  weekday     P6
4     4  weekday     P6

In [23]:
x.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   hour     48 non-null     int64
 1   weekday  48 non-null     str
 2   period   48 non-null     str
dtypes: int64(1), str(2)
memory usage: 1.3 KB

In [26]:
y = pd.read_csv('..\data\spanish_daily.csv')
y.head(-5)

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\Dario\AppData\Local\Temp\ipykernel_14016\2040707717.py:1: SyntaxWarning: invalid escape sequence '\d'
  y = pd.read_csv('..\data\spanish_daily.csv')
C:\Users\Dario\AppData\Local\Temp\ipykernel_14016\2040707717.py:1: DtypeWarning: Columns (0: id) have mixed types. Specify dtype option on import or set low_memory=False.
  y = pd.read_csv('..\data\spanish_daily.csv')

,id,year,month,day,max_t,min_t,gust_speed_w,gust_dir_w,avg_speed_w,precip,sunshine,max_pss,min_pss
0,0016A,1945,2,1,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1,0016A,1945,2,2,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
2,0016A,1945,2,3,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
3,0016A,1945,2,4,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
4,0016A,1945,2,5,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2138750,C929I,2012,9,21,29.1,22.9,34.92,160.0,15.84,0.0,8.3,1011.8,1009.9
2138751,C929I,2012,9,22,28.8,22.0,42.12,170.0,11.16,0.0,10.5,1010.8,1008.2
2138752,C929I,2012,9,23,29.3,22.8,45.00,110.0,23.04,0.0,7.6,1011.6,1008.9
2138753,C929I,2012,9,24,29.4,24.1,28.08,NaN,7.92,0.0,8.9,1013.3,1010.4
2138754,C929I,2012,9,25,28.8,24.6,34.92,NaN,10.08,0.0,7.2,NaN,NaN

In [25]:
y.info()

<class 'pandas.DataFrame'>
RangeIndex: 2138760 entries, 0 to 2138759
Data columns (total 13 columns):
 #   Column        Dtype
---  ------        -----
 0   id            object
 1   year          int64
 2   month         int64
 3   day           int64
 4   max_t         float64
 5   min_t         float64
 6   gust_speed_w  float64
 7   gust_dir_w    float64
 8   avg_speed_w   float64
 9   precip        float64
 10  sunshine      float64
 11  max_pss       float64
 12  min_pss       float64
dtypes: float64(9), int64(3), object(1)
memory usage: 212.1+ MB

In [28]:
w = pd.read_csv('..\data\spanish_monthly.csv')
w.head()

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\Dario\AppData\Local\Temp\ipykernel_14016\3464726903.py:1: SyntaxWarning: invalid escape sequence '\d'
  w = pd.read_csv('..\data\spanish_monthly.csv')

,id,year,month,avg_t,avg_max_t,avg_min_t,max_t,min_t,high_min_t,low_max_t,...,gust_speed_w,days_strong_w,days_very_strong_w,avg_speed_w,avg_daily_s,pct_s,avg_pss,max_pss,min_pss,avg_sfc_pss
0,0016A,1945,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0016A,1945,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0016A,1945,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0016A,1945,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0016A,1945,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
w.head(-5)

,id,year,month,avg_t,avg_max_t,avg_min_t,max_t,min_t,high_min_t,low_max_t,...,gust_speed_w,days_strong_w,days_very_strong_w,avg_speed_w,avg_daily_s,pct_s,avg_pss,max_pss,min_pss,avg_sfc_pss
0,0016A,1945,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0016A,1945,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0016A,1945,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0016A,1945,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0016A,1945,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73363,C929I,2011,12,20.4,21.8,19.0,24.8,16.8,20.7,19.9,...,68.04,12.0,0.0,27.00,5.4,52.0,1021.1,1029.5,1015.0,1024.9
73364,C929I,2012,1,19.2,20.8,17.5,23.1,16.0,18.5,19.0,...,55.08,1.0,0.0,20.88,5.9,56.0,1019.4,1027.8,1013.5,1023.2
73365,C929I,2012,2,17.6,19.1,16.1,20.5,14.2,17.6,17.6,...,74.16,9.0,0.0,27.00,5.8,52.0,1019.7,1027.9,1014.3,1023.5
73366,C929I,2012,3,18.8,20.4,17.1,24.2,16.0,18.1,18.3,...,60.84,9.0,0.0,24.12,6.9,57.0,1016.7,1026.2,1005.8,1020.4
73367,C929I,2012,4,18.9,21.2,16.6,22.9,11.2,18.0,17.8,...,66.96,4.0,0.0,24.12,7.4,58.0,1014.8,1022.1,1006.0,1018.5

In [3]:
w = pd.read_csv('..\data\clima_aemet_espana_media_diaria_2024.csv')

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\Dario\AppData\Local\Temp\ipykernel_16920\1609019229.py:1: SyntaxWarning: invalid escape sequence '\d'
  w = pd.read_csv('..\data\clima_aemet_espana_media_diaria_2024.csv')

In [4]:
w.info()

<class 'pandas.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   fecha           366 non-null    str
 1   tmed            366 non-null    float64
 2   tmin            366 non-null    float64
 3   tmax            366 non-null    float64
 4   prec            366 non-null    float64
 5   velmedia        366 non-null    float64
 6   racha           366 non-null    float64
 7   sol             366 non-null    float64
 8   presMax         366 non-null    float64
 9   presMin         366 non-null    float64
 10  num_estaciones  366 non-null    int64
dtypes: float64(9), int64(1), str(1)
memory usage: 31.6 KB