In [2]:
import pandas as pd

In [3]:
df_consumo = pd.read_csv(r"..\data\Steel_industry_data.csv")
df_consumo.head()

,date,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,CO2(tCO2),Lagging_Current_Power_Factor,Leading_Current_Power_Factor,NSM,WeekStatus,Day_of_week,Load_Type
0,01/01/2018 00:15,3.17,2.95,0.0,0.0,73.21,100.0,900,Weekday,Monday,Light_Load
1,01/01/2018 00:30,4.00,4.46,0.0,0.0,66.77,100.0,1800,Weekday,Monday,Light_Load
2,01/01/2018 00:45,3.24,3.28,0.0,0.0,70.28,100.0,2700,Weekday,Monday,Light_Load
3,01/01/2018 01:00,3.31,3.56,0.0,0.0,68.09,100.0,3600,Weekday,Monday,Light_Load
4,01/01/2018 01:15,3.82,4.50,0.0,0.0,64.72,100.0,4500,Weekday,Monday,Light_Load

In [4]:
df_consumo.info()

<class 'pandas.DataFrame'>
RangeIndex: 35040 entries, 0 to 35039
Data columns (total 11 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   date                                  35040 non-null  str
 1   Usage_kWh                             35040 non-null  float64
 2   Lagging_Current_Reactive.Power_kVarh  35040 non-null  float64
 3   Leading_Current_Reactive_Power_kVarh  35040 non-null  float64
 4   CO2(tCO2)                             35040 non-null  float64
 5   Lagging_Current_Power_Factor          35040 non-null  float64
 6   Leading_Current_Power_Factor          35040 non-null  float64
 7   NSM                                   35040 non-null  int64
 8   WeekStatus                            35040 non-null  str
 9   Day_of_week                           35040 non-null  str
 10  Load_Type                             35040 non-null  str
dtypes: float64(6), int64(1), str(4)
memory usage: 2.9 MB

In [5]:
columnas_consumo = {
    "date": "fecha_original",
    "Usage_kWh": "consumo_kwh",
    "Lagging_Current_Reactive.Power_kVarh": "reactiva_retrasada_kvarh",
    "Leading_Current_Reactive_Power_kVarh": "reactiva_adelantada_kvarh",
    "CO2(tCO2)": "CO2(tCO2)",
    "Lagging_Current_Power_Factor": "factor_potencia_retrasada",
    "Leading_Current_Power_Factor": "factor_potencia_adelantada",
    "NSM": "segundos_desde_medianoche",
    "WeekStatus": "tipo_semana",
    "Day_of_week": "dia_semana",
    "Load_Type": "tipo_carga"
}

df_consumo = df_consumo.rename(columns=columnas_consumo)

df_consumo.head()

,fecha_original,consumo_kwh,reactiva_retrasada_kvarh,reactiva_adelantada_kvarh,CO2(tCO2),factor_potencia_retrasada,factor_potencia_adelantada,segundos_desde_medianoche,tipo_semana,dia_semana,tipo_carga
0,01/01/2018 00:15,3.17,2.95,0.0,0.0,73.21,100.0,900,Weekday,Monday,Light_Load
1,01/01/2018 00:30,4.00,4.46,0.0,0.0,66.77,100.0,1800,Weekday,Monday,Light_Load
2,01/01/2018 00:45,3.24,3.28,0.0,0.0,70.28,100.0,2700,Weekday,Monday,Light_Load
3,01/01/2018 01:00,3.31,3.56,0.0,0.0,68.09,100.0,3600,Weekday,Monday,Light_Load
4,01/01/2018 01:15,3.82,4.50,0.0,0.0,64.72,100.0,4500,Weekday,Monday,Light_Load

In [6]:
df_consumo["datetime_original"] = pd.to_datetime(
    df_consumo["fecha_original"],
    dayfirst=True,
    errors="coerce"
)

df_consumo[["fecha_original", "datetime_original"]].head()

     fecha_original   datetime_original
0  01/01/2018 00:15 2018-01-01 00:15:00
1  01/01/2018 00:30 2018-01-01 00:30:00
2  01/01/2018 00:45 2018-01-01 00:45:00
3  01/01/2018 01:00 2018-01-01 01:00:00
4  01/01/2018 01:15 2018-01-01 01:15:00

In [7]:
df_consumo = df_consumo.sort_values("datetime_original").reset_index(drop=True)

df_consumo[["fecha_original", "datetime_original"]].head()

     fecha_original   datetime_original
0  01/01/2018 00:00 2018-01-01 00:00:00
1  01/01/2018 00:15 2018-01-01 00:15:00
2  01/01/2018 00:30 2018-01-01 00:30:00
3  01/01/2018 00:45 2018-01-01 00:45:00
4  01/01/2018 01:00 2018-01-01 01:00:00

In [8]:
calendario_2024_15min = pd.date_range(
    start="2024-01-01 00:00:00",
    end="2024-12-31 23:45:00",
    freq="15min"
)

len(calendario_2024_15min)

35136

In [9]:
calendario_consumo_real = calendario_2024_15min[:len(df_consumo)]

df_consumo["datetime_2024_simulado"] = calendario_consumo_real
df_consumo["origen_dato"] = "simulado_2024"

df_consumo[["datetime_original", "datetime_2024_simulado", "dia_semana", "origen_dato"]].head()

    datetime_original datetime_2024_simulado dia_semana    origen_dato
0 2018-01-01 00:00:00    2024-01-01 00:00:00     Monday  simulado_2024
1 2018-01-01 00:15:00    2024-01-01 00:15:00     Monday  simulado_2024
2 2018-01-01 00:30:00    2024-01-01 00:30:00     Monday  simulado_2024
3 2018-01-01 00:45:00    2024-01-01 00:45:00     Monday  simulado_2024
4 2018-01-01 01:00:00    2024-01-01 01:00:00     Monday  simulado_2024

In [10]:
df_1_enero_original = df_consumo.loc[
    df_consumo["datetime_original"].dt.date == pd.to_datetime("2018-01-01").date()
].copy()

df_1_enero_original.shape

(96, 14)

In [11]:
calendario_31d = pd.date_range(
    start="2024-12-31 00:00:00",
    end="2024-12-31 23:45:00",
    freq="15min"
)

len(calendario_31d)

96

In [12]:
df_31d = df_1_enero_original.copy()

# Cambiamos la fecha simulada al 31/12/2024
df_31d["datetime_2024_simulado"] = calendario_31d

# Marcamos el origen del dato
df_31d["fecha_original"] = "sintetico_31_diciembre_base_2018_01_01"
df_31d["datetime_original"] = pd.NaT
df_31d["origen_dato"] = "sintetico_31_diciembre"

# Recalculamos columnas temporales según el calendario 2024
df_31d["fecha"] = df_31d["datetime_2024_simulado"].dt.normalize()
df_31d["hora"] = df_31d["datetime_2024_simulado"].dt.hour
df_31d["dia"] = df_31d["datetime_2024_simulado"].dt.day
df_31d["mes"] = df_31d["datetime_2024_simulado"].dt.month
df_31d["dia_semana_2024"] = df_31d["datetime_2024_simulado"].dt.day_name()

# Recalculamos segundos desde medianoche
df_31d["segundos_desde_medianoche"] = (
    df_31d["datetime_2024_simulado"].dt.hour * 3600
    + df_31d["datetime_2024_simulado"].dt.minute * 60
)

# Ajustamos las columnas categóricas de calendario al 31/12/2024
# 31/12/2024 fue martes y día entre semana.
df_31d["tipo_semana"] = "Weekday"
df_31d["dia_semana"] = "Tuesday"

df_31d.head()

,fecha_original,consumo_kwh,reactiva_retrasada_kvarh,reactiva_adelantada_kvarh,CO2(tCO2),factor_potencia_retrasada,factor_potencia_adelantada,segundos_desde_medianoche,tipo_semana,dia_semana,tipo_carga,datetime_original,datetime_2024_simulado,origen_dato,fecha,hora,dia,mes,dia_semana_2024
0,sintetico_31_diciembre_base_2018_01_01,3.42,3.46,0.0,0.0,70.30,100.0,0,Weekday,Tuesday,Light_Load,NaT,2024-12-31 00:00:00,sintetico_31_diciembre,2024-12-31,0,31,12,Tuesday
1,sintetico_31_diciembre_base_2018_01_01,3.17,2.95,0.0,0.0,73.21,100.0,900,Weekday,Tuesday,Light_Load,NaT,2024-12-31 00:15:00,sintetico_31_diciembre,2024-12-31,0,31,12,Tuesday
2,sintetico_31_diciembre_base_2018_01_01,4.00,4.46,0.0,0.0,66.77,100.0,1800,Weekday,Tuesday,Light_Load,NaT,2024-12-31 00:30:00,sintetico_31_diciembre,2024-12-31,0,31,12,Tuesday
3,sintetico_31_diciembre_base_2018_01_01,3.24,3.28,0.0,0.0,70.28,100.0,2700,Weekday,Tuesday,Light_Load,NaT,2024-12-31 00:45:00,sintetico_31_diciembre,2024-12-31,0,31,12,Tuesday
4,sintetico_31_diciembre_base_2018_01_01,3.31,3.56,0.0,0.0,68.09,100.0,3600,Weekday,Tuesday,Light_Load,NaT,2024-12-31 01:00:00,sintetico_31_diciembre,2024-12-31,1,31,12,Tuesday

In [15]:
df_consumo_2024 = pd.concat(
    [df_consumo, df_31d],
    ignore_index=True)

In [16]:
df_consumo_2024.info()

<class 'pandas.DataFrame'>
RangeIndex: 35136 entries, 0 to 35135
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   fecha_original              35136 non-null  str
 1   consumo_kwh                 35136 non-null  float64
 2   reactiva_retrasada_kvarh    35136 non-null  float64
 3   reactiva_adelantada_kvarh   35136 non-null  float64
 4   CO2(tCO2)                   35136 non-null  float64
 5   factor_potencia_retrasada   35136 non-null  float64
 6   factor_potencia_adelantada  35136 non-null  float64
 7   segundos_desde_medianoche   35136 non-null  int64
 8   tipo_semana                 35136 non-null  str
 9   dia_semana                  35136 non-null  str
 10  tipo_carga                  35136 non-null  str
 11  datetime_original           35040 non-null  datetime64[ns]
 12  datetime_2024_simulado      35136 non-null  datetime64[us]
 13  origen_dato                 35136 non-null  str
 14  fecha                       96 non-null     datetime64[us]
 15  hora                        96 non-null     float64
 16  dia                         96 non-null     float64
 17  mes                         96 non-null     float64
 18  dia_semana_2024             96 non-null     str
dtypes: datetime64[ns](1), datetime64[us](2), float64(9), int64(1), str(6)
memory usage: 5.1 MB

In [17]:
# ============================================================
# CREACIÓN DEL DATAFRAME DE ESTUDIO PARA EL EDA
# ============================================================

# Creamos un nuevo DataFrame solo con las columnas útiles para el análisis.
# A partir de este punto trabajaremos con fechas simuladas de 2024.
# Las columnas de fecha original 2018 se dejan fuera del DataFrame de estudio.

columnas_estudio = [
    "datetime_2024_simulado",
    "fecha",
    "hora",
    "dia",
    "mes",
    "dia_semana_2024",
    "tipo_semana",
    "tipo_carga",
    "consumo_kwh",
    "reactiva_retrasada_kvarh",
    "reactiva_adelantada_kvarh",
    "CO2(tCO2)",
    "factor_potencia_retrasada",
    "factor_potencia_adelantada",
    "segundos_desde_medianoche",
    "origen_dato"
]

df_consumo_2024_estudio = df_consumo_2024[columnas_estudio].copy()

In [18]:
df_consumo_2024_estudio.head()

,datetime_2024_simulado,fecha,hora,dia,mes,dia_semana_2024,tipo_semana,tipo_carga,consumo_kwh,reactiva_retrasada_kvarh,reactiva_adelantada_kvarh,CO2(tCO2),factor_potencia_retrasada,factor_potencia_adelantada,segundos_desde_medianoche,origen_dato
0,2024-01-01 00:00:00,NaT,NaN,NaN,NaN,NaN,Weekday,Light_Load,3.42,3.46,0.0,0.0,70.30,100.0,0,simulado_2024
1,2024-01-01 00:15:00,NaT,NaN,NaN,NaN,NaN,Weekday,Light_Load,3.17,2.95,0.0,0.0,73.21,100.0,900,simulado_2024
2,2024-01-01 00:30:00,NaT,NaN,NaN,NaN,NaN,Weekday,Light_Load,4.00,4.46,0.0,0.0,66.77,100.0,1800,simulado_2024
3,2024-01-01 00:45:00,NaT,NaN,NaN,NaN,NaN,Weekday,Light_Load,3.24,3.28,0.0,0.0,70.28,100.0,2700,simulado_2024
4,2024-01-01 01:00:00,NaT,NaN,NaN,NaN,NaN,Weekday,Light_Load,3.31,3.56,0.0,0.0,68.09,100.0,3600,simulado_2024

In [19]:
df_consumo_2024_estudio.info()

<class 'pandas.DataFrame'>
RangeIndex: 35136 entries, 0 to 35135
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   datetime_2024_simulado      35136 non-null  datetime64[us]
 1   fecha                       96 non-null     datetime64[us]
 2   hora                        96 non-null     float64
 3   dia                         96 non-null     float64
 4   mes                         96 non-null     float64
 5   dia_semana_2024             96 non-null     str
 6   tipo_semana                 35136 non-null  str
 7   tipo_carga                  35136 non-null  str
 8   consumo_kwh                 35136 non-null  float64
 9   reactiva_retrasada_kvarh    35136 non-null  float64
 10  reactiva_adelantada_kvarh   35136 non-null  float64
 11  CO2(tCO2)                   35136 non-null  float64
 12  factor_potencia_retrasada   35136 non-null  float64
 13  factor_potencia_adelantada  35136 non-null  float64
 14  segundos_desde_medianoche   35136 non-null  int64
 15  origen_dato                 35136 non-null  str
dtypes: datetime64[us](2), float64(9), int64(1), str(4)
memory usage: 4.3 MB

In [20]:
# ============================================================
# 1. CREACIÓN DE COLUMNA HORA_PERIODO
# ============================================================

# Creamos una hora de periodo de 1 a 24:
# 00:00, 00:15, 00:30, 00:45 -> hora_periodo = 1
# 01:00, 01:15, 01:30, 01:45 -> hora_periodo = 2
# ...
# 23:00, 23:15, 23:30, 23:45 -> hora_periodo = 24

df_consumo_2024_estudio["hora_periodo"] = (
    df_consumo_2024_estudio["hora"] + 1
)

df_consumo_2024_estudio[[
    "datetime_2024_simulado",
    "fecha",
    "hora",
    "hora_periodo",
    "consumo_kwh"
]].head(10)

  datetime_2024_simulado fecha  hora  hora_periodo  consumo_kwh
0    2024-01-01 00:00:00   NaT   NaN           NaN         3.42
1    2024-01-01 00:15:00   NaT   NaN           NaN         3.17
2    2024-01-01 00:30:00   NaT   NaN           NaN         4.00
3    2024-01-01 00:45:00   NaT   NaN           NaN         3.24
4    2024-01-01 01:00:00   NaT   NaN           NaN         3.31
5    2024-01-01 01:15:00   NaT   NaN           NaN         3.82
6    2024-01-01 01:30:00   NaT   NaN           NaN         3.28
7    2024-01-01 01:45:00   NaT   NaN           NaN         3.60
8    2024-01-01 02:00:00   NaT   NaN           NaN         3.60
9    2024-01-01 02:15:00   NaT   NaN           NaN         3.28

In [21]:
# ============================================================
# 2. VALIDACIÓN DE 4 REGISTROS POR FECHA Y HORA_PERIODO
# ============================================================

df_consumo_2024_estudio.groupby(
    ["fecha", "hora_periodo"]
).size().value_counts()

4    24
Name: count, dtype: int64

In [22]:
# ============================================================
# 3. AGRUPACIÓN HORARIA POR FECHA Y HORA_PERIODO
# ============================================================

df_consumo_hora = (
    df_consumo_2024_estudio
    .groupby(["fecha", "hora_periodo"], as_index=False)
    .agg({
        "dia": "first",
        "mes": "first",
        "dia_semana_2024": "first",
        "tipo_semana": "first",
        "tipo_carga": "first",
        "consumo_kwh": "sum",
        "reactiva_retrasada_kvarh": "sum",
        "reactiva_adelantada_kvarh": "sum",
        "CO2(tCO2)": "sum",
        "factor_potencia_retrasada": "mean",
        "factor_potencia_adelantada": "mean",
        "origen_dato": "first"
    })
)

df_consumo_hora.head()

,fecha,hora_periodo,dia,mes,dia_semana_2024,tipo_semana,tipo_carga,consumo_kwh,reactiva_retrasada_kvarh,reactiva_adelantada_kvarh,CO2(tCO2),factor_potencia_retrasada,factor_potencia_adelantada,origen_dato
0,2024-12-31,1.0,31.0,12.0,Tuesday,Weekday,Light_Load,13.83,14.15,0.0,0.0,70.1400,100.0,sintetico_31_diciembre
1,2024-12-31,2.0,31.0,12.0,Tuesday,Weekday,Light_Load,14.01,15.76,0.0,0.0,66.5475,100.0,sintetico_31_diciembre
2,2024-12-31,3.0,31.0,12.0,Tuesday,Weekday,Light_Load,14.12,16.67,0.0,0.0,64.7400,100.0,sintetico_31_diciembre
3,2024-12-31,4.0,31.0,12.0,Tuesday,Weekday,Light_Load,13.82,16.20,0.0,0.0,65.0675,100.0,sintetico_31_diciembre
4,2024-12-31,5.0,31.0,12.0,Tuesday,Weekday,Light_Load,14.47,17.64,0.0,0.0,63.5175,100.0,sintetico_31_diciembre

In [23]:
# ============================================================
# 4. CREACIÓN DE DATETIME_HORA
# ============================================================

df_consumo_hora["datetime_hora"] = (
    df_consumo_hora["fecha"]
    + pd.to_timedelta(df_consumo_hora["hora_periodo"] - 1, unit="h")
)

df_consumo_hora.head()

,fecha,hora_periodo,dia,mes,dia_semana_2024,tipo_semana,tipo_carga,consumo_kwh,reactiva_retrasada_kvarh,reactiva_adelantada_kvarh,CO2(tCO2),factor_potencia_retrasada,factor_potencia_adelantada,origen_dato,datetime_hora
0,2024-12-31,1.0,31.0,12.0,Tuesday,Weekday,Light_Load,13.83,14.15,0.0,0.0,70.1400,100.0,sintetico_31_diciembre,2024-12-31 00:00:00
1,2024-12-31,2.0,31.0,12.0,Tuesday,Weekday,Light_Load,14.01,15.76,0.0,0.0,66.5475,100.0,sintetico_31_diciembre,2024-12-31 01:00:00
2,2024-12-31,3.0,31.0,12.0,Tuesday,Weekday,Light_Load,14.12,16.67,0.0,0.0,64.7400,100.0,sintetico_31_diciembre,2024-12-31 02:00:00
3,2024-12-31,4.0,31.0,12.0,Tuesday,Weekday,Light_Load,13.82,16.20,0.0,0.0,65.0675,100.0,sintetico_31_diciembre,2024-12-31 03:00:00
4,2024-12-31,5.0,31.0,12.0,Tuesday,Weekday,Light_Load,14.47,17.64,0.0,0.0,63.5175,100.0,sintetico_31_diciembre,2024-12-31 04:00:00

In [24]:
# ============================================================
# 5. REORDENACIÓN DEL DATAFRAME HORARIO
# ============================================================

columnas_hora_ordenadas = [
    "datetime_hora",
    "fecha",
    "hora_periodo",
    "dia",
    "mes",
    "dia_semana_2024",
    "tipo_semana",
    "tipo_carga",
    "consumo_kwh",
    "reactiva_retrasada_kvarh",
    "reactiva_adelantada_kvarh",
    "CO2(tCO2)",
    "factor_potencia_retrasada",
    "factor_potencia_adelantada",
    "origen_dato"
]

df_consumo_hora = df_consumo_hora[columnas_hora_ordenadas]

df_consumo_hora.head()

,datetime_hora,fecha,hora_periodo,dia,mes,dia_semana_2024,tipo_semana,tipo_carga,consumo_kwh,reactiva_retrasada_kvarh,reactiva_adelantada_kvarh,CO2(tCO2),factor_potencia_retrasada,factor_potencia_adelantada,origen_dato
0,2024-12-31 00:00:00,2024-12-31,1.0,31.0,12.0,Tuesday,Weekday,Light_Load,13.83,14.15,0.0,0.0,70.1400,100.0,sintetico_31_diciembre
1,2024-12-31 01:00:00,2024-12-31,2.0,31.0,12.0,Tuesday,Weekday,Light_Load,14.01,15.76,0.0,0.0,66.5475,100.0,sintetico_31_diciembre
2,2024-12-31 02:00:00,2024-12-31,3.0,31.0,12.0,Tuesday,Weekday,Light_Load,14.12,16.67,0.0,0.0,64.7400,100.0,sintetico_31_diciembre
3,2024-12-31 03:00:00,2024-12-31,4.0,31.0,12.0,Tuesday,Weekday,Light_Load,13.82,16.20,0.0,0.0,65.0675,100.0,sintetico_31_diciembre
4,2024-12-31 04:00:00,2024-12-31,5.0,31.0,12.0,Tuesday,Weekday,Light_Load,14.47,17.64,0.0,0.0,63.5175,100.0,sintetico_31_diciembre

In [25]:
# ============================================================
# 7. VALIDACIÓN DE CONSERVACIÓN DEL CONSUMO TOTAL
# ============================================================

consumo_total_15min = df_consumo_2024_estudio["consumo_kwh"].sum()
consumo_total_hora = df_consumo_hora["consumo_kwh"].sum()

print("Consumo total 15 min:", round(consumo_total_15min, 2))
print("Consumo total horario:", round(consumo_total_hora, 2))
print("Diferencia:", round(consumo_total_15min - consumo_total_hora, 6))

Consumo total 15 min: 959988.57
Consumo total horario: 351.86
Diferencia: 959636.71

In [26]:
df_consumo_hora.info()

<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   datetime_hora               24 non-null     datetime64[us]
 1   fecha                       24 non-null     datetime64[us]
 2   hora_periodo                24 non-null     float64
 3   dia                         24 non-null     float64
 4   mes                         24 non-null     float64
 5   dia_semana_2024             24 non-null     str
 6   tipo_semana                 24 non-null     str
 7   tipo_carga                  24 non-null     str
 8   consumo_kwh                 24 non-null     float64
 9   reactiva_retrasada_kvarh    24 non-null     float64
 10  reactiva_adelantada_kvarh   24 non-null     float64
 11  CO2(tCO2)                   24 non-null     float64
 12  factor_potencia_retrasada   24 non-null     float64
 13  factor_potencia_adelantada  24 non-null     float64
 14  origen_dato                 24 non-null     str
dtypes: datetime64[us](2), float64(9), str(4)
memory usage: 2.9 KB

In [27]:
# ============================================================
# CREACIÓN DEL DATAFRAME FINAL DE CONSUMO HORARIO LIMPIO
# ============================================================

df_consumo_2024_horario_estudio_limpio = df_consumo_hora.copy()

In [28]:
df_consumo_2024_horario_estudio_limpio.to_csv(
    r"..\data_limpios\df_consumo_2024_horario_estudio_limpio.csv",
    index=False,
    encoding="utf-8-sig"
)

In [29]:
df_periodos = pd.read_csv(r"..\data\periodos_peninsula.csv")
df_periodos.head()

  Time Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec Weekend
0  0-1  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6      P6
1  1-2  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6      P6
2  2-3  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6      P6
3  3-4  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6      P6
4  4-5  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6      P6

In [30]:
# ============================================================
# 1. CARGA DEL NUEVO DATASET DE PERIODOS TARIFARIOS
# ============================================================

df_periodos = pd.read_csv(r"..\data\periodos_peninsula.csv")

df_periodos.head()

  Time Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec Weekend
0  0-1  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6      P6
1  1-2  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6      P6
2  2-3  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6      P6
3  3-4  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6      P6
4  4-5  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6  P6      P6

In [31]:
df_periodos.info()

<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Time     24 non-null     str
 1   Jan      24 non-null     str
 2   Feb      24 non-null     str
 3   Mar      24 non-null     str
 4   Apr      24 non-null     str
 5   May      24 non-null     str
 6   Jun      24 non-null     str
 7   Jul      24 non-null     str
 8   Aug      24 non-null     str
 9   Sep      24 non-null     str
 10  Oct      24 non-null     str
 11  Nov      24 non-null     str
 12  Dec      24 non-null     str
 13  Weekend  24 non-null     str
dtypes: str(14)
memory usage: 2.8 KB

In [32]:
# ============================================================
# 3. DICCIONARIO DE MESES
# ============================================================

mapa_meses = {
    "Jan": 1,
    "Feb": 2,
    "Mar": 3,
    "Apr": 4,
    "May": 5,
    "Jun": 6,
    "Jul": 7,
    "Aug": 8,
    "Sep": 9,
    "Oct": 10,
    "Nov": 11,
    "Dec": 12
}

In [33]:
# ============================================================
# 4. TRANSFORMACIÓN DE LUNES A VIERNES A FORMATO LARGO
# ============================================================

columnas_meses = list(mapa_meses.keys())

df_periodos_weekday = df_periodos.melt(
    id_vars="Time",
    value_vars=columnas_meses,
    var_name="mes_texto",
    value_name="periodo_tarifario"
)

df_periodos_weekday["mes"] = df_periodos_weekday["mes_texto"].map(mapa_meses)
df_periodos_weekday["tipo_semana"] = "Weekday"

df_periodos_weekday.head()

  Time mes_texto periodo_tarifario  mes tipo_semana
0  0-1       Jan                P6    1     Weekday
1  1-2       Jan                P6    1     Weekday
2  2-3       Jan                P6    1     Weekday
3  3-4       Jan                P6    1     Weekday
4  4-5       Jan                P6    1     Weekday

In [34]:
# ============================================================
# 5. TRANSFORMACIÓN DE FINES DE SEMANA A FORMATO LARGO
# ============================================================

filas_weekend = []

for mes_texto, mes_numero in mapa_meses.items():
    df_temp = df_periodos[["Time", "Weekend"]].copy()
    df_temp["mes_texto"] = mes_texto
    df_temp["mes"] = mes_numero
    df_temp["tipo_semana"] = "Weekend"
    df_temp = df_temp.rename(columns={"Weekend": "periodo_tarifario"})
    filas_weekend.append(df_temp)

df_periodos_weekend = pd.concat(filas_weekend, ignore_index=True)

df_periodos_weekend.head()

  Time periodo_tarifario mes_texto  mes tipo_semana
0  0-1                P6       Jan    1     Weekend
1  1-2                P6       Jan    1     Weekend
2  2-3                P6       Jan    1     Weekend
3  3-4                P6       Jan    1     Weekend
4  4-5                P6       Jan    1     Weekend

In [35]:
# ============================================================
# 6. UNIÓN DE WEEKDAY Y WEEKEND
# ============================================================

df_periodos_limpio = pd.concat(
    [df_periodos_weekday, df_periodos_weekend],
    ignore_index=True
)

df_periodos_limpio.head()

  Time mes_texto periodo_tarifario  mes tipo_semana
0  0-1       Jan                P6    1     Weekday
1  1-2       Jan                P6    1     Weekday
2  2-3       Jan                P6    1     Weekday
3  3-4       Jan                P6    1     Weekday
4  4-5       Jan                P6    1     Weekday

In [36]:
# ============================================================
# 7. CREACIÓN DE HORA_INICIO, HORA_FIN Y HORA_PERIODO
# ============================================================

df_periodos_limpio[["hora_inicio", "hora_fin"]] = (
    df_periodos_limpio["Time"]
    .str.split("-", expand=True)
    .astype(int)
)

df_periodos_limpio["hora_periodo"] = df_periodos_limpio["hora_inicio"] + 1

df_periodos_limpio.head()

,Time,mes_texto,periodo_tarifario,mes,tipo_semana,hora_inicio,hora_fin,hora_periodo
0,0-1,Jan,P6,1,Weekday,0,1,1
1,1-2,Jan,P6,1,Weekday,1,2,2
2,2-3,Jan,P6,1,Weekday,2,3,3
3,3-4,Jan,P6,1,Weekday,3,4,4
4,4-5,Jan,P6,1,Weekday,4,5,5

In [37]:
# ============================================================
# 8. REORDENACIÓN FINAL DE COLUMNAS
# ============================================================

df_periodos_limpio = df_periodos_limpio[
    [
        "mes",
        "mes_texto",
        "tipo_semana",
        "hora_periodo",
        "hora_inicio",
        "hora_fin",
        "Time",
        "periodo_tarifario"
    ]
]

df_periodos_limpio = df_periodos_limpio.sort_values(
    ["mes", "tipo_semana", "hora_periodo"]
).reset_index(drop=True)

df_periodos_limpio.head()

,mes,mes_texto,tipo_semana,hora_periodo,hora_inicio,hora_fin,Time,periodo_tarifario
0,1,Jan,Weekday,1,0,1,0-1,P6
1,1,Jan,Weekday,2,1,2,1-2,P6
2,1,Jan,Weekday,3,2,3,2-3,P6
3,1,Jan,Weekday,4,3,4,3-4,P6
4,1,Jan,Weekday,5,4,5,4-5,P6

In [38]:
df_periodos_limpio.info()

<class 'pandas.DataFrame'>
RangeIndex: 576 entries, 0 to 575
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   mes                576 non-null    int64
 1   mes_texto          576 non-null    str
 2   tipo_semana        576 non-null    str
 3   hora_periodo       576 non-null    int64
 4   hora_inicio        576 non-null    int64
 5   hora_fin           576 non-null    int64
 6   Time               576 non-null    str
 7   periodo_tarifario  576 non-null    str
dtypes: int64(4), str(4)
memory usage: 36.1 KB

In [39]:
# ============================================================
# 14. GUARDADO DEL DATASET LIMPIO DE PERIODOS
# ============================================================

df_periodos_limpio.to_csv(
    r"..\data_limpios\df_periodos_peninsula_limpio.csv",
    index=False,
    encoding="utf-8-sig"
)

In [40]:


# ============================================================
# 1. CARGA DEL DATASET DE CLIMA 2024
# ============================================================

df_clima = pd.read_csv(r"..\data\clima_aemet_espana_media_diaria_2024.csv")


# ============================================================
# 2. RENOMBRADO DE COLUMNAS
# ============================================================

df_clima_2024_limpio = df_clima.rename(columns={
    "fecha": "fecha",
    "tmed": "temperatura_media",
    "tmin": "temperatura_minima",
    "tmax": "temperatura_maxima",
    "prec": "precipitacion",
    "velmedia": "viento_medio",
    "racha": "racha_viento",
    "sol": "horas_sol",
    "presMax": "presion_maxima",
    "presMin": "presion_minima",
    "num_estaciones": "num_estaciones"
}).copy()


# ============================================================
# 3. CONVERSIÓN DE FECHA A DATETIME
# ============================================================

df_clima_2024_limpio["fecha"] = pd.to_datetime(
    df_clima_2024_limpio["fecha"],
    errors="coerce"
)


# ============================================================
# 4. CREACIÓN DE COLUMNAS TEMPORALES
# ============================================================

df_clima_2024_limpio["dia"] = df_clima_2024_limpio["fecha"].dt.day
df_clima_2024_limpio["mes"] = df_clima_2024_limpio["fecha"].dt.month
df_clima_2024_limpio["dia_semana"] = df_clima_2024_limpio["fecha"].dt.day_name()
df_clima_2024_limpio["dia_anio"] = df_clima_2024_limpio["fecha"].dt.dayofyear


# ============================================================
# 5. REORDENACIÓN FINAL DE COLUMNAS
# ============================================================

columnas_clima_ordenadas = [
    "fecha",
    "dia",
    "mes",
    "dia_semana",
    "dia_anio",
    "temperatura_media",
    "temperatura_minima",
    "temperatura_maxima",
    "precipitacion",
    "viento_medio",
    "racha_viento",
    "horas_sol",
    "presion_maxima",
    "presion_minima",
    "num_estaciones"
]

df_clima_2024_limpio = df_clima_2024_limpio[columnas_clima_ordenadas]


# ============================================================
# 6. GUARDADO DEL DATASET LIMPIO DE CLIMA
# ============================================================

df_clima_2024_limpio.to_csv(
    r"..\data_limpios\df_clima_2024_limpio.csv",
    index=False,
    encoding="utf-8-sig"
)